# Generated by Django 3.1.1 on 2020-09-20 06:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address', models.TextField(blank=True, default='')),
                ('mobile_no', models.CharField(blank=True, max_length=10)),
                ('whatsapp_no', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MilkModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milk_type', models.CharField(choices=[('Cow', 'Cow'), ('Buffalo', 'Buffalo')], max_length=30, verbose_name='Milk Type')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'ordering': ['rate'],
                'unique_together': {('milk_type', 'rate')},
            },
        ),
        migrations.CreateModel(
            name='RecordsModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.customermodel')),
                ('milk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.milkmodel')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
